# Generated by Django 5.2.4 on 2025-07-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
